### PR TITLE
Add ssl support

### PR DESCRIPTION
**Pull request by stephenreay**
This should provide a fix for the mysql part of #12

### CODE REVIEW

**Comment by gabfl** [comment]
Thank you. I will test it and look into the PostgreSQL situation!

**Comment by gabfl** [comment]
HI @stephenreay, how does your branch works if the ssl flags are not in the config file?

**Comment by stephenreay** [comment]
Without the ssl config items the underlying pymysql will just make a regular tcp connection to the server. Is that what you meant?

**Review by gabfl — APPROVED** [review]
Tested with the following config:
```
root@client:~# cat .dbschema.yml
databases:
    db2:
        engine: mysql
        host: (remote_ip)
        port: 3306
        user: remote_user
        password: my_password
        ssl_ca: /etc/mysql/client-ssl/ca-cert.pem

        ssl_check_hostname: false # set to false to disable hostname checking of the server cert
        ssl_cert: /etc/mysql/client-ssl/client-cert.pem
        ssl_key: /etc/mysql/client-ssl/client-key.pem
        # ssl_cipher: 'cipher-name'
        ssl_capath: /etc/mysql/client-ssl/
        db: my_db
        path: /root/migrations/
        pre_migration: ''
        post_migration: ''
root@client:~# 
```

Migrations and rollback works:
```
root@client:~# dbschema
 * Applying migrations for db2 (`my_db` on mysql)
   -> Migration `migration1` applied
 * Migrations applied

root@client:~# dbschema -r migration1 --tag db2
 * Rolling back db2 (`my_db` on mysql)
   -> Migration `migration1` has been rolled back
root@client:~# 
```

**Comment by gabfl** [comment]
thanks again @stephenreay, apologies for the delay to review it, I had to stage a server to test the feature

**Comment by stephenreay** [comment]
Hey no worries. I should have included my Vagrant config I guess.

**Pull request merged**
